version: '3'

tasks:
  coverage:
    silent: true
    cmds:
      - go test -race -covermode=atomic -cover ./...
  test:
    cmds:
      - go install gotest.tools/gotestsum@latest
      - gotestsum --format=short-verbose -- -race -v ./...
  lint:
    cmds:
      - go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.49
      - golangci-lint run
  fix:
    cmds:
      - go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.49
      - golangci-lint run --fix
  build:
    desc: Build
    cmds:
      - go build \
        -ldflags='-w -s -X github.com/owner/repository/core.store.Version=:version' \
        -gcflags=all='-l' \
        -o bin/:bin github.com/owner/repository/cmd/:bin

