on:
  push:
    paths-ignore:
      - 'README.md'
  pull_request:
    paths-ignore:
      - 'README.md'
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          stable: false # if you want to use an unstable version of Go
          go-version: 1.16
      - run: go test -v -race -coverprofile=coverage.txt -covermode=atomic ./...
      - run: bash <(curl -S https://codecov.io/bash)